# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-18 17:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=4000)),
                ('start_money', models.PositiveIntegerField()),
                ('start_position', models.PositiveIntegerField(default=0)),
                ('num_houses', models.PositiveIntegerField()),
                ('num_hotels', models.PositiveIntegerField()),
                ('turn_time', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_action', models.DateTimeField(null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engine.Board')),
            ],
        ),
        migrations.CreateModel(
            name='OwnedSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveIntegerField(default=0)),
                ('in_jail', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='engine.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7)),
                ('house_cost', models.PositiveIntegerField()),
                ('hotel_cost', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RailroadGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_cost', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Buyable',
            fields=[
                ('space_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='engine.Space')),
                ('price', models.PositiveIntegerField()),
                ('mortgage', models.PositiveIntegerField(null=True)),
            ],
            bases=('engine.space',),
        ),
        migrations.AddField(
            model_name='space',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spaces', to='engine.Board'),
        ),
        migrations.AddField(
            model_name='ownedspace',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engine.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='current_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='engine.Player'),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('buyable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='engine.Buyable')),
                ('rent', models.PositiveIntegerField()),
                ('rent_colorset', models.PositiveIntegerField(null=True)),
                ('rent_1_house', models.PositiveIntegerField()),
                ('rent_2_house', models.PositiveIntegerField()),
                ('rent_3_house', models.PositiveIntegerField()),
                ('rent_4_house', models.PositiveIntegerField()),
                ('rent_hotel', models.PositiveIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engine.PropertyGroup')),
            ],
            bases=('engine.buyable',),
        ),
        migrations.CreateModel(
            name='Railroad',
            fields=[
                ('buyable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='engine.Buyable')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engine.RailroadGroup')),
            ],
            bases=('engine.buyable',),
        ),
        migrations.AlterUniqueTogether(
            name='space',
            unique_together=set([('board', 'position')]),
        ),
        migrations.AddField(
            model_name='ownedspace',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engine.Buyable'),
        ),
    ]
